Dmitrii issue33 flask-login
estem8/LP_PFM pull request #40
Opened 2024-01-03 16:08 UTC by Dmitrii-U

Прикрутил Flask-login, добавил хеширование пароля и проверку пароля.
Перенес логику login и logout в blueprint user, сломал тесты)
Удалил .vscode/settings.json и webapp.db  - этого не должно быть в репе

Ветка основана на ветке dmitrii_issue39_linters и включает все изменения из неё, т.к. её еще не мержили.

2024-01-05 07:51 UTC, lwof requested changes

2024-01-05 07:51 UTC, lwof commented on app/user/models.py
> +    def set_passwords(self, password):
Мне кажется, что тут не нужно множественное окончание s.

2024-01-05 07:51 UTC, lwof commented on app/crud.py
>          user = User(login=login, password=password, email=email)
Можно ли убрать password из вызова конструктора? Если получится, то стоит убрать, что бы не вводить в заблуждение никого.

2024-01-05 07:51 UTC, lwof commented on app/test/test_database.py
> +    engine = create_engine(current_app.config.DB_URL, echo=True)
Вроде задумка неплохая, но в тестах может быть неудобно. А в чем была идея изначально это сделать?

2024-01-05 07:51 UTC, lwof commented on app/user/models.py
> +    """Пользователи"""
Допиши плиз в доке что добавляет UserMixin

2024-01-05 07:51 UTC, lwof commented on app/user/models.py
> +    login: Mapped[str]
Это кажется тоже должно быть mapped_column, что бы алхимия сохраняла эти атрибуты в бд

2024-01-06 07:12 UTC, Dmitrii-U commented on app/user/models.py
> +    def set_passwords(self, password):
исправил

2024-01-06 07:12 UTC, Dmitrii-U commented on app/crud.py
>          user = User(login=login, password=password, email=email)
убрал

2024-01-06 07:14 UTC, Dmitrii-U commented on app/test/test_database.py
> +    engine = create_engine(current_app.config.DB_URL, echo=True)
При запуске тестов в данный момент никак не присходит создание переменных окружения.
Это если только самому создавать, а это не правильно.
Переписал на использование
`from app.config import DB_URL`

2024-01-07 10:16 UTC, Dmitrii-U commented on app/user/models.py
> +    """Пользователи"""
дописал

2024-01-07 10:41 UTC, Dmitrii-U commented on app/user/models.py
> +    login: Mapped[str]
![Screenshot from 2024-01-07 13-37-21](https://github.com/estem8/LP_PFM/assets/153464653/ba93ee6d-22b6-48d6-8c36-b9323690e6b2)
Ботает с  login: Mapped[str]

2024-01-07 11:48 UTC, merged