Сохраняем новые счета в БД
estem8/LP_PFM pull request #49
Opened 2024-01-12 10:45 UTC by estem8

Fixes #43

2024-01-12 11:49 UTC, lwof commented on app/edit/views.py
> +    if request.method == "POST" and form.validate():
Давай добавим при помощи flash вывод какого-то разумного сообщения в случае если форма не завалидировалась?
Для этого я бы в базовый шаблон добавил бы единственное место где мы будем вытаскивать все сообщения при помощи get_flashed_messages

2024-01-12 11:49 UTC, lwof commented on app/edit/forms.py
> +    account_name = StringField("account name", [validators.Length(min=1, max=25)])
Кавычки то изменения линтера? Хотелось бы что бы мы использовали какой-то один только вариант кавычек.

2024-01-12 19:03 UTC, lwof commented on app/edit/views.py
> +    if request.method == "POST" and form.validate():
Что бы не затягивать с этим ПР, можно просто добавить туду  с номером тикета в этом месте и создать тикет на будущее

2024-01-17 19:47 UTC, Dmitrii-U requested changes

2024-01-17 20:07 UTC, merged