Сделать сохранение пользователей при регистрации в БД
estem8/LP_PFM pull request #51
Opened 2024-01-12 17:54 UTC by estem8

Fixes #41

2024-01-16 12:26 UTC, lwof requested changes

2024-01-16 12:26 UTC, lwof commented on app/crud.py
> +from sqlite3 import IntegrityError
Это кажется не используется

2024-01-16 12:26 UTC, lwof commented on app/crud.py
> +        except exc.IntegrityError:
Я так понял, что ты здесь пытался проверять разные случаи ошибок, если существует более чем одна запись в БД. 
Давай будем считать count(), и если он не равен нулю, значит нельзя создавать пользователя. 

Но самым ровным путем было бы так же добавить unique constrain к логину. 
Тогда логика упрощается еще больше:
1. Пробуем создать пользователя. 
2. Если перехватили IntegrityError, значит пользователь уже существует. 

В такой схеме есть преимущество, что мы сразу пресекаем мутные баги а что если два запроса на создание пользователя отправить одновременно. Сама база данных выступает гарантом того что только одна запись будет создана. (А базы данных хорошо это делают)

2024-01-16 12:26 UTC, lwof commented on app/user/forms.py
> +        validators=[DataRequired(), Length(min=1, max=50)],
Можно еще EmailValidator навесить (это отдельный пакет). 
А про длину не уверен надо ли это чекать.

2024-01-16 12:26 UTC, lwof commented on app/user/models.py
> +    def __init__(self, data):
Хех, как много раз я видел этот метод 🥲
Добавь хоть аннотацию, что data это дикт.

2024-01-16 12:26 UTC, lwof commented on app/user/views.py
> +@blueprint.route("/signup", methods=["POST", "GET"], endpoint='registration')
может для эндпоинта использовать такое-же имя siginup? Легко запутаться.

2024-01-16 12:26 UTC, lwof commented on app/user/views.py
> +        return redirect(url_for("index"))
Мы же договорились что у нас одинарные кавычки (вроде?)

2024-01-16 12:26 UTC, lwof commented on app/user/views.py
> +    if request.method == "POST" and reg_form.validate():
Кажется достаточно `if form.validate_on_submit():`

2024-01-16 12:26 UTC, lwof commented on app/user/views.py
> +        new_user(reg_form.data)
По хорошему бы после регистрации перенаправить пользователя на другую страницу чем сайнап. Можно создать profile, или на страничку где будут отображаться аккаунты пользователя.

2024-01-16 12:26 UTC, lwof commented on app/user/views.py
> +@blueprint.route('/process-login', methods=['GET', 'POST'])
А зачем гет сюда добавил?

2024-01-16 12:26 UTC, lwof commented on db_init.py
> +    #так что мне кажется эту функцию можно пихать в app/__init__.py на каждый запуск
Все так. Попробуй переписать комент в чуть более официальном стиле, что бы у человека читающего его через 3 года было меньше вопросов (кто "я"?). Можешь добавить ссылку на доку алхимии если хочешь.

2024-01-16 12:31 UTC, estem8 commented on app/crud.py
> +
fix
```suggestion
from flask import flash, redirect, url_for
```

2024-01-16 12:32 UTC, estem8 commented on app/crud.py
> +from sqlalchemy import inspect
fix
```suggestion
from sqlalchemy import exc
```

2024-01-16 12:33 UTC, estem8 commented on app/crud.py
> +    smth = select(User).where(User.login == new_user.login)
Не понял ошибки

2024-01-16 12:49 UTC, estem8 commented on app/models.py
> +class Base(DeclarativeBase):
Кажется что имеено тут должно быть все что касается описания базы
```suggestion
class Base(DeclarativeBase):
```

2024-01-16 12:53 UTC, estem8 commented on app/user/models.py
> +    def __init__(self, data):
Это плохой метод или?

2024-01-16 13:02 UTC, estem8 commented on app/user/views.py
> +    if request.method == "POST" and reg_form.validate():
Да в 
https://flask-wtf.readthedocs.io/en/0.15.x/quickstart/#validating-forms 
говорится что if form.validate_on_submit() под капотом имеет == POST
но тогда пропадает Дзен python 'явное лучше неявного' или это про другое? :))
```suggestion
    if request.method == "POST" and reg_form.validate():
```

2024-01-17 19:49 UTC, Dmitrii-U requested changes

2024-01-17 20:06 UTC, merged