Реализовал сохранение транзакций в БД.
estem8/LP_PFM pull request #56
Opened 2024-01-14 17:25 UTC by Dmitrii-U

Добавил черновики формы, шаблона. Добавил тесты сохранения и записи изменения транзакций в БД.

2024-01-15 09:14 UTC, lwof requested changes

2024-01-15 09:14 UTC, lwof commented on app/transactions/models.py
> +class Transaction(Base):
Субъективно, я бы предпочел хранить все ORM модели в одном месте, а не растаскивать по модулям. 

Мотивация такая: модели из разных модулей будут использовать друг друга, и почти все места бизнес логики будут использовать несколько моделей одновременно. 
Очень быстро это приведет к Circular Import проблемам, которые придется фиксить костылями вроде if TYPE_CHECKING, и импортов на уровне функций. 

Побочная плюшка от хранения моделей в отдельном файле, ты можешь его подключить к стороннему скрипту и работать с сущностями БД напрямую. А если модели будут размазаны по разным модулям это усложнит их использование вне проекта. 

Вообще, когда думаешь про разделение кода, мне нравится такая эвристика: как разделить код на части таким образом, что бы количество ссылок между файлами (читай импортов) было минимальным. При этом внутри каждой отдельной части код был бы сильно связанным.

2024-01-15 09:14 UTC, lwof commented on app/transactions/models.py
> +    amount: Mapped[int]
У меня есть стойкое ощущение, что без `mapped_column(Integer)` алхимия не будет создавать колонки в БД. Потому что без assignment operator это просто аннотированный атрибут класса.

2024-01-15 09:14 UTC, lwof commented on app/transactions/models.py
> +    comment: Mapped[Optional[str]]
Вероятно мы не хотим Optional[str] 
Нас вполне устроило бы использовать пустую строку в случае если пользователь не указал комент. Упрощай типы когда это возможно.

2024-01-15 09:14 UTC, lwof commented on app/transactions/models.py
> +    updated_at: Mapped[Optional[datetime]] = mapped_column(default=datetime.utcnow, onupdate=datetime.utcnow)
Аналогично. Как минимум всегда можно задавать updated_at равным created_at

2024-01-15 09:14 UTC, lwof commented on app/user/views.py
> +    title = 'Вход'
Было бы здорово выделить эти "косметические" правки в отдельный ПР, просто что бы не ревьюить много кода за раз. Ну это так, на будущее.

2024-01-15 09:14 UTC, lwof commented on app/config.py
> +    'dept'  # код расходной операции. т.к. в БД нет таблицы с типами операций, то оно живет тут
Мб позже это будет иметь смысл поменять на enum, но пока оставляй так - посмотрим как этот список будет использоваться. 
Здорово, что вынес это в отдельную константу👍

2024-01-18 18:18 UTC, Dmitrii-U commented on app/transactions/models.py
> +class Transaction(Base):
Вернул все модели в зад

2024-01-18 22:58 UTC, Dmitrii-U commented on app/transactions/models.py
> +    amount: Mapped[int]
Создает)

2024-01-18 22:59 UTC, Dmitrii-U commented on app/transactions/models.py
> +    comment: Mapped[Optional[str]]
Упростил

2024-01-18 23:01 UTC, Dmitrii-U commented on app/transactions/models.py
> +    updated_at: Mapped[Optional[datetime]] = mapped_column(default=datetime.utcnow, onupdate=datetime.utcnow)
Ломается вставка в БД если я пишу     
`updated_at: Mapped[Optional[datetime]] = mapped_column(default=created_at, onupdate=datetime.utcnow)`

2024-01-19 07:04 UTC, lwof requested changes
Было бы не здорово мерджить с закоментированными кусками кода.

2024-01-19 07:04 UTC, lwof commented on app/transactions/views.py
> +    return  # TODO придумать, куда переводить пользователя
```suggestion
    form = TransactionForm()
    if form.validate_on_submit():
        try:
            create_transaction(form.data)
        except DatabaseError:
            flash('Ошибка создания транзакции')
    else:
        flash('Невалидная форма')
    return render_template('transactions/add.html', page_title=page_title, form=form)
```
Мне кажется хорошо бы придерживаться такой структуры для эндпоинтов. Могу на созвоне словами объяснить почему это хорошо. Но основной тезис - то что так проще всего структура. Один return, и в случае ошибки валидации мы так же возвращаем пользователю уже заполненную форму.

2024-01-19 07:04 UTC, lwof commented on app/transactions/views.py
> +    return  # TODO придумать, куда переводить пользователя
А ну, еще в try-else можно добавить редирект в случае успешного создания.

2024-01-19 10:29 UTC, estem8 requested changes

2024-01-19 10:29 UTC, estem8 commented on app/crud.py
> +        except DatabaseError as e:
except Exception as e: был написано для того что бы отлавливать все ошибки а там их
https://docs.python.org/3/library/sqlite3.html#exceptions

2024-01-19 17:31 UTC, estem8 commented on app/transactions/models.py
> +    updated_at: Mapped[Optional[datetime]] = mapped_column(default=datetime.utcnow, onupdate=datetime.utcnow)
Надо вызывать из sql onupdate=func.now())

2024-01-19 20:06 UTC, Dmitrii-U commented on app/crud.py
> +        except DatabaseError as e:
Это ссылка на БД sqlite3, а у нас SQLAlchemy, которая астрагирует уровень БД

Чекни Too broad exception clause

2024-01-19 22:41 UTC, Dmitrii-U commented on app/crud.py
> +                                                      ).update(**transaction_data, synchronize_session='evaluate')
Был молодой зеленый погорячился...

Переписал

2024-01-20 15:30 UTC, lwof commented on app/common.py
> +class DtaBaseUniqError(Exception):
Data
```suggestion
class DataBaseUniqError(Exception):
```

2024-01-20 22:25 UTC, merged