issue-74 не работает получение текущего пользователя
estem8/LP_PFM pull request #75
Opened 2024-01-30 03:05 UTC by Dmitrii-U

2024-01-30 16:04 UTC, lwof requested changes

2024-01-30 16:04 UTC, lwof commented on app/currency.json
> +[
сделать этот файл просто py файлом, облегчило бы дальнейшую работу с ним. Не нужно читать его через json.loads(), сразу бери-импортируй.

2024-01-30 16:04 UTC, lwof commented on app/currency.json
> +[
А если еще и туплом его объявить....

2024-01-30 16:04 UTC, lwof commented on app/transactions/views.py
> +    if request.method == 'GET':
По идее эта ветка if не должна влиять на работу функции.

2024-01-30 16:04 UTC, lwof commented on app/user/views.py
> +blueprint = Blueprint('user', __name__, url_prefix='/users', template_folder='templates', static_folder='static')
аналогично, нам незачем указывать свои директории для статики и шаблонов

2024-01-31 21:37 UTC, Dmitrii-U commented on app/__init__.py
> +        if 'AnonymousUserMixin' in exception.args[0]:
Так точно!
Убрал handle_attr_error

2024-01-31 21:38 UTC, Dmitrii-U commented on app/__init__.py
> -        print(session)
добавил

2024-01-31 21:38 UTC, Dmitrii-U commented on app/account/views.py
> +@flask_login.login_required
ок

2024-01-31 21:39 UTC, Dmitrii-U commented on app/account/views.py
> +blueprint = Blueprint('account', __name__, url_prefix='/account', template_folder='templates', static_folder='static')
убрал

2024-02-01 02:42 UTC, Dmitrii-U commented on app/account/views.py
> +blueprint = Blueprint('account', __name__, url_prefix='/account', template_folder='templates', static_folder='static')
убрал

2024-02-01 02:51 UTC, Dmitrii-U commented on app/user/views.py
> +blueprint = Blueprint('user', __name__, url_prefix='/users', template_folder='templates', static_folder='static')
убрал

2024-02-01 02:51 UTC, Dmitrii-U commented on app/currency.json
> +[
сделал

2024-02-02 21:30 UTC, Dmitrii-U commented on app/account/views.py
> +    account_data.pop('submit')
переделал

2024-02-02 21:32 UTC, Dmitrii-U commented on app/crud.py
> +def fetch_account(data: dict[str, Any], user: User) -> Account:
переделал

2024-02-02 21:36 UTC, Dmitrii-U commented on app/crud.py
> +    db.session.execute(
сделал

2024-02-03 02:33 UTC, Dmitrii-U commented on app/account/views.py
> +        creat_account(account_data)
исправил

2024-02-03 02:42 UTC, Dmitrii-U commented on app/transactions/views.py
> +    if request.method == 'GET':
Переписал это

2024-02-03 08:34 UTC, merged